# Generated by Django 4.0.4 on 2022-09-16 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carosuel',
            fields=[
                ('carosuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('carosuel_image', models.ImageField(upload_to='carosuel_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', tinymce.models.HTMLField()),
                ('url', models.CharField(max_length=100)),
                ('cat_image', models.ImageField(upload_to='card_images/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', tinymce.models.HTMLField()),
                ('url', models.CharField(max_length=100)),
                ('post_image', models.ImageField(upload_to='post_images/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_btn', models.BooleanField(default=False)),
                ('like_on', models.DateTimeField()),
                ('log_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.post')),
                ('particular_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_btn_d', models.BooleanField(default=False)),
                ('like_on_d', models.DateTimeField()),
                ('log_post_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.post')),
                ('particular_user_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('comment_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.post')),
            ],
        ),
    ]
